### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks

**Comment by sakshamtaneja21** [comment]
thank you
may i know where we have to send our shipping address to receive swags 
refer https://www.jabref.org/hacktoberfest/2019.html

**Comment by koppor** [comment]
I put "invalid" here. The pull request contained the addition of two letters and the change of one character. They are good enough to merged in.

Hacktoberfest has "Quality standards". See https://hacktoberfest.digitalocean.com/details.
The motto is "Quality" is key. 

grafik

Touching less then 10 letters (!) is too less to count towards a T-Shirt.

Did you see our disclaimer statement at https://www.jabref.org/hacktoberfest/2019.html.

grafik

Our swag is **one sticker**

grafik

If you insist on getting this sticker and putting it somewhere on your laptop, I can send it to you. We are a group of volunteers paying the sticker and the mailing fee privately. If you I would ask you that you provide us a photo in return where you put it so that we can celebrate hacktoberfest here and be happy that our campaign lead to something.

**Comment by sakshamtaneja21** [comment]
sure 
i would love to get sticker

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by koppor** [comment]
So, please find our public email address on our homepage and write us an email with your shipping address.

**Pull request merged**
